### ISSUE TITLE
Integration is not working on 2026.3

### ISSUE THREAD

**Issue by steiale** [pytoyoda/ha_toyota#243]
**Describe the bug**
Login is failing. Hence integration fails

**To Reproduce**
Just login. It fails with unexpected error.

**Expected behavior**
Login and fetching data. 

**Screenshots**

**Additional context**
2026.3 Changes ssh and python version. It should be done with an updated linking.

**Comment by Leeser** [comment]
Same issue, tried the above fix. But didn't work.

Am running the latest version of HA.

 MyToyota app is logging in correctly.

This was an issue this morning before I updated HA, all my sensors were unavailable. Removed toyota integration and then reinstalled with the newest version.

On configuration, put in login details (correctly) and just an "Unexpected error" and can't get past the login page.

Any advice gratefully accepted.


Adding in log here for info:

Logger: custom_components.toyota.config_flow
Source: custom_components/toyota/config_flow.py:72
integration: Toyota EU community integration ([documentation](https://github.com/pytoyoda/ha_toyota), [issues](https://github.com/pytoyoda/ha_
toyota/issues))
First occurred: 8:56:56 PM (2 occurrences)
Last logged: 8:57:12 PM

An unknown error occurred during login request.
Traceback (most recent call last):
  File "/config/custom_components/toyota/config_flow.py", line 72, in async_step_user
    await client.login()
  File "/usr/local/lib/python3.14/site-packages/pytoyoda/client.py", line 90, in login
    await self._api.controller.login()
  File "/usr/local/lib/python3.14/site-packages/pytoyoda/controller.py", line 113, in login
    await self._update_token()
  File "/usr/local/lib/python3.14/site-packages/pytoyoda/controller.py", line 133, in _update_token
    await self._authenticate()
  File "/usr/local/lib/python3.14/site-packages/pytoyoda/controller.py", line 145, in _authenticate
    async with self._get_http_client() as client:
               ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.14/contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/pytoyoda/controller.py", line 138, in _get_http_client
    async with hishel.AsyncCacheClient(timeout=self._timeout) as client:
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'hishel' has no attribute 'AsyncCacheClient'


Update 15:20. 6/3/26

Removed and then installed v2.2.2

All working now

Much appreciated.

**Comment by firstandlast1966** [comment]
I managed to get the integration working, but now the figures are in KM rather than Miles. Is there a way of changing it to Miles again. I did look for a setting and study the code but couldn't find anything obvious. Thanks.

LOL just found it.

**Comment by fcoval** [comment]
**I am unable to log in to integration v2.2.0 :**

Método de instalación
Home Assistant OS
Core
2026.3.0
Supervisor
2026.02.3
Operating System
17.1
Frontend
20260304.0
************************************************************
Registrador: custom_components.toyota.config_flow
Fuente: custom_components/toyota/config_flow.py:72
integración: Toyota EU community integration ([documentación](https://github.com/pytoyoda/ha_toyota), [problemas](https://github.com/pytoyoda/ha_toyota/issues))
Ocurrió por primera vez: 21:52:18 (1 ocurrencia)
Última vez registrado: 21:52:18

An unknown error occurred during login request.
Traceback (most recent call last):
  File "/config/custom_components/toyota/config_flow.py", line 72, in async_step_user
    await client.login()
  File "/usr/local/lib/python3.14/site-packages/pytoyoda/client.py", line 90, in login
    await self._api.controller.login()
  File "/usr/local/lib/python3.14/site-packages/pytoyoda/controller.py", line 113, in login
    await self._update_token()
  File "/usr/local/lib/python3.14/site-packages/pytoyoda/controller.py", line 133, in _update_token
    await self._authenticate()
  File "/usr/local/lib/python3.14/site-packages/pytoyoda/controller.py", line 145, in _authenticate
    async with self._get_http_client() as client:
               ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.14/contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/pytoyoda/controller.py", line 138, in _get_http_client
    async with hishel.AsyncCacheClient(timeout=self._timeout) as client:
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'hishel' has no attribute 'AsyncCacheClient'

**Comment by Gonzo345** [comment]
> > I updated to update released today and still didn't work.
> 
> Argh, worked for me, will look into it more tomorrow, maybe someone else figures it out by then.
> Can you attach the logs from HA? Any errors from this should be in Settings -> System -> Logs

Hey, don't worry! We all know shit happens!

This is what I have been able to recover from logs before performing the manual workaround
` [31m2026-03-05 15:19:10.547 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx@gmail.com for toyota
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 769, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/toyota/__init__.py", line 131, in async_setup_entry
    await hass.async_add_executor_job(_sync_login)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/config/custom_components/toyota/__init__.py", line 126, in _sync_login
    result = loop.run_until_complete(client.login())
  File "/usr/local/lib/python3.14/asyncio/base_events.py", line 719, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.14/site-packages/pytoyoda/client.py", line 90, in login
    await self._api.controller.login()
  File "/usr/local/lib/python3.14/site-packages/pytoyoda/controller.py", line 113, in login
    await self._update_token()
  File "/usr/local/lib/python3.14/site-packages/pytoyoda/controller.py", line 133, in _update_token
    await self._authenticate()
  File "/usr/local/lib/python3.14/site-packages/pytoyoda/controller.py", line 145, in _authenticate
    async with self._get_http_client() as client:
               ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.14/contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/pytoyoda/controller.py", line 138, in _get_http_client
    async with hishel.AsyncCacheClient(timeout=self._timeout) as client:
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'hishel' has no attribute 'AsyncCacheClient'[0m `

**Comment by max571958** [comment]
Hi, I updated HA to version 2026.3 and MyToyota EU to 2.2.0, but I'm still getting the "Unexpected Error" error. I tried the workaround, but it doesn't work. I'll wait for the bug to be fixed; I hope it won't take too long. 🙁

**Comment by majestro84** [comment]
After Update to 2.2.0 and adding this part `hishel<1.0` in manifest.json, it`s works.
Thx @fabiovit 

> Go to /config/custom_components/toyota/manifest.json and replace with this:
> 
> { "domain": "toyota", "name": "Toyota EU community integration", "after_dependencies": [ "cloud", "http" ], "codeowners": [ "[@deejay1](https://github.com/deejay1)", "[@CM000n](https://github.com/CM000n)" ], "config_flow": true, "documentation": "https://github.com/pytoyoda/ha_toyota", "iot_class": "cloud_polling", "issue_tracker": "https://github.com/pytoyoda/ha_toyota/issues", "requirements": [ "pytoyoda>=4.1.0,<5.0", "arrow", "hishel<1.0" ], "version": "2.1.0" }

**Comment by deejay1** [comment]
Please try 2.2.1

**Comment by leeb9972** [comment]
> Please try 2.2.1
Perfect, back working for me, updated to 2.2.1 !! Thank you @deejay1

**Comment by Anangaranga** [comment]
> Please try 2.2.1

Works very well now ! Many thanks for your help @deejay1  and the others ! Have a nice day !

**Comment by CM000n** [comment]
Duplicate of https://github.com/pytoyoda/ha_toyota/issues/241
